### ISSUE TITLE
django 1.7 support

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler-web#9]
With django 1.7 when accessing the web interface I get:
~~~~~
AppRegistryNotReady at /

Apps aren't loaded yet.

[Tue May 12 09:06:11.621573 2015] [wsgi:error] [pid 32530] No handlers could be found for logger "django.request"
~~~~~
Looks like one replaces:
replace
~~~~~
import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
~~~~~
with
~~~~~
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
~~~~~
But I'm not sure how to do this in a backwards compatible way, if possible.  Changing this certainly breaks cobbler-web on django 1.4

**Comment by opoplawski** [comment]
This isn't sufficient either, other errors follow.

**Comment by opoplawski** [comment]
Actually, it might be - but we use _application.

**Comment by jschaef** [comment]
Hi, 
I have no knowledge about django and limited knowledge about python but found the solution due to 
some google research:

replace in /usr/share/cobbler/web/cobbler.wsgi:
import django.core.handlers.wsgi
_application = django.core.handlers.wsgi.WSGIHandler()

by:
from django.core.wsgi import get_wsgi_application
_application = get_wsgi_application()

**Comment by jmaas** [comment]
moved to cobbler/#1488
sorry for inconvenience.
